### PR TITLE
New tests cases with matchers using wildcards

### PR DESCRIPTION
**Pull request by abhayachauhan**

### CODE REVIEW

**Comment by bethesque** [comment]
Sorry for the delay on this, I've got some bench time over the next few days, so I will look at it ASAP.

**Comment by abhayachauhan** [comment]
No rush - take your time ;)

**Comment by uglyog** [comment]
These look correct to me.

**Comment by uglyog** [comment]
I've had to modify your test cases slightly. For the cases where there is a list, there needs to be a type matcher defined on the list otherwise matching will fail due to the size being different.

For instance, the following example should fail:

```json
{
  "match": false,
  "comment": "array with type matcher",
  "expected": {
    "headers": {},
    "body" : {
      "myDates": [
        10
      ]
    },
    "matchingRules" : {
      "$.body.myDates[*]" : {
        "match": "type"
      }
    }
  },
  "actual": {
    "headers": {},
    "body": {
      "myDates": [
        20,
        5,
        1910
      ]
    }    
  }
}
```

because although all the items in the list will match by type, the arrays are different sizes.

The correct test would be:

```json
{
  "match": true,
  "comment": "array with type matcher",
  "expected": {
    "headers": {},
    "body" : {
      "myDates": [
        10
      ]
    },
    "matchingRules" : {
      "$.body.myDates" : {
        "match": "type"
      },
      "$.body.myDates[*]" : {
        "match": "type"
      }
    }
  },
  "actual": {
    "headers": {},
    "body": {
      "myDates": [
        20,
        5,
        1910
      ]
    }    
  }
}
```

**Comment by uglyog** [comment]
I have also noticed that `objects in array type matching.json` the keys where a different case.

**Pull request merged**
